# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
#xcode_scheme: CoreGPX
#xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  
  - xcodebuild -workspace Example/CoreGPX.xcworkspace -scheme CoreGPX -sdk iphonesimulator12.1 -destination 'OS=12.1,name=iPhone XS' | xcpretty;
  - xcodebuild -workspace Example/CoreGPX.xcworkspace -scheme CoreGPX-watchOS -sdk watchsimulator5.1 -destination 'OS=5.1,name=Apple Watch Series 4 - 44mm' | xcpretty;
  - xcodebuild -workspace Example/CoreGPX.xcworkspace -scheme CoreGPX-macOS -sdk macosx10.14 -destination 'arch=x86_64' | xcpretty;
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GPXKit.xcworkspace -scheme GPXKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
