name: CoreGPX CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'

jobs:
  iOS:
    name: iOS Build
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Build CoreGPX iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "Example/CoreGPX.xcworkspace" -scheme "CoreGPX" -destination "OS=14.3,name=iPhone 12 Pro" clean build | xcpretty
      
  macOS:
    name: macOS Build
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    strategy:
      matrix:
        name: ["Build CoreGPX macOS", "Build CoreGPX macOS Catalyst"]
        scheme: ["CoreGPX-macOS", "CoreGPX"]
    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.name }}
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Example/CoreGPX.xcworkspace" -scheme "${{ matrix.scheme }}" -destination "platform=macOS" clean build | xcpretty
      
  watchOS:
    name: watchOS Build
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build CoreGPX watchOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Alamofire.xcodeproj" -scheme "CoreGPX-watchOS" -destination "OS=7.2,name=Apple Watch Series 6 - 44mm" clean build | xcpretty
  
  example:     
    name: Example App Build
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Build Example App
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "Example/CoreGPX.xcworkspace" -scheme "CoreGPX-Example" -destination "OS=14.3,name=iPhone 12 Pro" clean build | xcpretty
