name: CoreGPX CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - '*'
env: 
  DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
jobs:
  iOS:
    name: iOS Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build CoreGPX iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "Example/CoreGPX.xcworkspace" -scheme "CoreGPX" -destination "OS=15.5,name=iPhone 12 Pro" clean build | xcpretty
      
  macOS:
    name: macOS Build
    runs-on: macos-12
    strategy:
      matrix:
        config:
          - { name: "macOS", scheme: "CoreGPX-macOS" }
          - { name: "Mac Catalyst", scheme: "CoreGPX" }
    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.config['name'] }}
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "Example/CoreGPX.xcworkspace" -scheme "${{ matrix.config['scheme'] }}" -destination "platform=macOS" clean build | xcpretty
      
  watchOS:
    name: watchOS Build
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build CoreGPX watchOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "Example/CoreGPX.xcworkspace" -scheme "CoreGPX-watchOS" -destination "OS=8.5,name=Apple Watch Series 6 - 44mm" clean build | xcpretty
  
  example:     
    name: Build Example & Test
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Build Example App
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "Example/CoreGPX.xcworkspace" -scheme "CoreGPX-Example" -destination "OS=15.5,name=iPhone 12 Pro" clean build | xcpretty
    - name: Run test cases
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "Example/CoreGPX.xcworkspace" -scheme "CoreGPX Tests" -destination "OS=15.5,name=iPhone 12 Pro" test | xcpretty
     
